name: InfinityExpansion
author: Mooy1
description: more slimefun content
main: io.github.mooy1.infinityexpansion.InfinityExpansion
website: https://github.com/Mooy1/InfinityExpansion
depend: [Slimefun]
softdepend: [LiteXpansion]
version: ${project.version}
api-version: 1.16

commands:
  infinityexpansion:
    description: Use /infinityexpansion help for a list of commands
    usage: /infinityexpansion <subcommand>
    aliases: [ie, ix, infinity]

permissions:
  infinityexpansion.setdata:
    description: Access to /infinityexpansion setdata
    default: op
  infinityexpansion.printitem:
    description: Access to /infinityexpansion printitem
    default: op
  infinityexpansion.giverecipe:
    description: Access to /infinityexpansion giverecipe
    default: op

